export default function buildMails(prenom, nom) {

    // TODO Gérer les nom de famille composé ou à particule

    const mails = [];
    nom = nom.replace(' ', '').replace('-', '');
    if (prenom.includes('-')) {
        prenom = [prenom.split('-')[0], prenom.split('-')[1]];
        mails.push(prenom[0]);
        mails.push(prenom[1]);
        mails.push(prenom[0] + prenom[1]);
        mails.push(prenom[0] + '.' + prenom[1]);
        mails.push(prenom[0] + '-' + prenom[1]);
        mails.push(nom);
        mails.push(prenom[0] + nom);
        mails.push(prenom[1] + nom);
        mails.push(prenom[0] + prenom[1] + nom);
        mails.push(prenom[0] + '.' + prenom[1] + nom);
        mails.push(prenom[0] + '-' + prenom[1] + nom);
        mails.push(prenom[0] + '.' + nom);
        mails.push(prenom[1] + '.' + nom);
        mails.push(prenom[0] + prenom[1] + '.' + nom);
        mails.push(prenom[0] + '.' + prenom[1] + '.' + nom);
        mails.push(prenom[0] + '-' + prenom[1] + '.' + nom);
        mails.push(prenom[0] + '-' + nom);
        mails.push(prenom[1] + '-' + nom);
        mails.push(prenom[0] + prenom[1] + '-' + nom);
        mails.push(prenom[0] + '.' + prenom[1] + '-' + nom);
        mails.push(prenom[0] + '-' + prenom[1] + '-' + nom);
        mails.push(prenom[0].slice(0, 1) + nom);
        mails.push(prenom[1].slice(0, 1) + nom);
        mails.push(prenom[0].slice(0, 1) + prenom[1].slice(0, 1) + nom);
        mails.push(prenom[0].slice(0, 1) + '.' + prenom[1].slice(0, 1) + nom);
        mails.push(prenom[0].slice(0, 1) + '-' + prenom[1].slice(0, 1) + nom);
        mails.push(prenom[0].slice(0, 1) + '.' + nom);
        mails.push(prenom[1].slice(0, 1) + '.' + nom);
        mails.push(prenom[0].slice(0, 1) + prenom[1].slice(0, 1) + '.' + nom);
        mails.push(prenom[0].slice(0, 1) + '.' + prenom[1].slice(0, 1) + '.' + nom);
        mails.push(prenom[0].slice(0, 1) + '-' + prenom[1].slice(0, 1) + '.' + nom);
        mails.push(prenom[0].slice(0, 1) + '-' + nom);
        mails.push(prenom[1].slice(0, 1) + '-' + nom);
        mails.push(prenom[0].slice(0, 1) + prenom[1].slice(0, 1) + '-' + nom);
        mails.push(prenom[0].slice(0, 1) + '.' + prenom[1].slice(0, 1) + '-' + nom);
        mails.push(prenom[0].slice(0, 1) + '-' + prenom[1].slice(0, 1) + '-' + nom);
        mails.push(prenom[0] + nom.slice(0, 1));
        mails.push(prenom[1] + nom.slice(0, 1));
        mails.push(prenom[0] + prenom[1] + nom.slice(0, 1));
        mails.push(prenom[0] + '.' + prenom[1] + nom.slice(0, 1));
        mails.push(prenom[0] + '-' + prenom[1] + nom.slice(0, 1));
        mails.push(prenom[0] + '.' + nom.slice(0, 1));
        mails.push(prenom[1] + '.' + nom.slice(0, 1));
        mails.push(prenom[0] + prenom[1] + '.' + nom.slice(0, 1));
        mails.push(prenom[0] + '.' + prenom[1] + '.' + nom.slice(0, 1));
        mails.push(prenom[0] + '-' + prenom[1] + '.' + nom.slice(0, 1));
        mails.push(prenom[0] + '-' + nom.slice(0, 1));
        mails.push(prenom[1] + '-' + nom.slice(0, 1));
        mails.push(prenom[0] + prenom[1] + '-' + nom.slice(0, 1));
        mails.push(prenom[0] + '.' + prenom[1] + '-' + nom.slice(0, 1));
        mails.push(prenom[0] + '-' + prenom[1] + '-' + nom.slice(0, 1));
        mails.push(nom + prenom[0]);
        mails.push(nom + prenom[1]);
        mails.push(nom + prenom[0] + prenom[1]);
        mails.push(nom + prenom[0] + '.' + prenom[1]);
        mails.push(nom + prenom[0] + '-' + prenom[1]);
        mails.push(nom + '.' + prenom[0]);
        mails.push(nom + '.' + prenom[1]);
        mails.push(nom + '.' + prenom[0] + prenom[1]);
        mails.push(nom + '.' + prenom[0] + '.' + prenom[1]);
        mails.push(nom + '.' + prenom[0] + '-' + prenom[1]);
        mails.push(nom + '-' + prenom[0]);
        mails.push(nom + '-' + prenom[1]);
        mails.push(nom + '-' + prenom[0] + prenom[1]);
        mails.push(nom + '-' + prenom[0] + '.' + prenom[1]);
        mails.push(nom + '-' + prenom[0] + '-' + prenom[1]);
        mails.push(nom + prenom[0].slice(0, 1));
        mails.push(nom + prenom[1].slice(0, 1));
        mails.push(nom + prenom[0].slice(0, 1) + prenom[1].slice(0, 1));
        mails.push(nom + prenom[0].slice(0, 1) + '.' + prenom[1].slice(0, 1));
        mails.push(nom + prenom[0].slice(0, 1) + '-' + prenom[1].slice(0, 1));
        mails.push(nom + '.' + prenom[0].slice(0, 1));
        mails.push(nom + '.' + prenom[1].slice(0, 1));
        mails.push(nom + '.' + prenom[0].slice(0, 1) + prenom[1].slice(0, 1));
        mails.push(nom + '.' + prenom[0].slice(0, 1) + '.' + prenom[1].slice(0, 1));
        mails.push(nom + '.' + prenom[0].slice(0, 1) + '-' + prenom[1].slice(0, 1));
        mails.push(nom + '-' + prenom[0].slice(0, 1));
        mails.push(nom + '-' + prenom[1].slice(0, 1));
        mails.push(nom + '-' + prenom[0].slice(0, 1) + prenom[1].slice(0, 1));
        mails.push(nom + '-' + prenom[0].slice(0, 1) + '.' + prenom[1].slice(0, 1));
        mails.push(nom + '-' + prenom[0].slice(0, 1) + '-' + prenom[1].slice(0, 1));
        mails.push(nom.slice(0, 1) + prenom[0]);
        mails.push(nom.slice(0, 1) + prenom[1]);
        mails.push(nom.slice(0, 1) + prenom[0] + prenom[1]);
        mails.push(nom.slice(0, 1) + prenom[0] + '.' + prenom[1]);
        mails.push(nom.slice(0, 1) + prenom[0] + '-' + prenom[1]);
        mails.push(nom.slice(0, 1) + '.' + prenom[0]);
        mails.push(nom.slice(0, 1) + '.' + prenom[1]);
        mails.push(nom.slice(0, 1) + '.' + prenom[0] + prenom[1]);
        mails.push(nom.slice(0, 1) + '.' + prenom[0] + '.' + prenom[1]);
        mails.push(nom.slice(0, 1) + '.' + prenom[0] + '-' + prenom[1]);
        mails.push(nom.slice(0, 1) + '-' + prenom[0]);
        mails.push(nom.slice(0, 1) + '-' + prenom[1]);
        mails.push(nom.slice(0, 1) + '-' + prenom[0] + prenom[1]);
        mails.push(nom.slice(0, 1) + '-' + prenom[0] + '.' + prenom[1]);
        mails.push(nom.slice(0, 1) + '-' + prenom[0] + '-' + prenom[1]);
    } else {
        mails.push(prenom);
        mails.push(nom);
        mails.push(prenom + nom);
        mails.push(prenom + '.' + nom);
        mails.push(prenom + '-' + nom);
        mails.push(prenom.slice(0, 1) + nom);
        mails.push(prenom.slice(0, 1) + '.' + nom);
        mails.push(prenom.slice(0, 1) + '-' + nom);
        mails.push(prenom + nom.slice(0, 1));
        mails.push(prenom + '.' + nom.slice(0, 1));
        mails.push(prenom + '-' + nom.slice(0, 1));
        mails.push(nom + prenom);
        mails.push(nom + '.' + prenom);
        mails.push(nom + '-' + prenom);
        mails.push(nom + prenom.slice(0, 1));
        mails.push(nom + '.' + prenom.slice(0, 1));
        mails.push(nom + '-' + prenom.slice(0, 1));
        mails.push(nom.slice(0, 1) + prenom);
        mails.push(nom.slice(0, 1) + '.' + prenom);
        mails.push(nom.slice(0, 1) + '-' + prenom);
    }
    return mails;
}